export class AppConfig{
  public static serverIp="66.112.222.22";
  public static BDUSS = "WRFTHplfmZzcjJDS3RRV3J1YmpzRH53R05ta3ZqanJSejVNNk11OGxzRX52UTljQVFBQUFBJCQAAAAAAAAAAAEAAADrH1bpAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD8w6Fs~MOhbO";
}
